//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetalineProAgent.Business
{


    public partial class DeliveryRate
    {

        /// <summary>
        /// plcDeliRulesControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plcDeliRulesControls;

        /// <summary>
        /// ctrlDeliveryRuleHL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RetalineProAgent.Controls.ctrlDeliveryRule ctrlDeliveryRuleHL;

        /// <summary>
        /// ctrlDeliveryRuleLoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RetalineProAgent.Controls.ctrlDeliveryRule ctrlDeliveryRuleLoc;

        /// <summary>
        /// ctrlDeliveryRuleLong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RetalineProAgent.Controls.ctrlDeliveryRule ctrlDeliveryRuleLong;

        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
