using RetalineProAgent.Core.Services;
using RetalineProAgent.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace RetalineProAgent.Controls.SignupControl
{
	public partial class ctrlSignupResetPassword : Base.BasePartnerUserControl
	{
		public string PasswordVerifyKey
		{
			get
			{
				if (ViewState["PSWVERFKEY"] == null)
					return "";

				return ViewState["PSWVERFKEY"].ToString();
			}
			set
			{
				ViewState["PSWVERFKEY"] = value;
			}

		}
		public PswViewType CurPswViewType
		{
			get
			{
				if (ViewState["CURPSWVIEWTYPE"] == null)
					return PswViewType.InvalidKey;

				return (PswViewType)ViewState["CURPSWVIEWTYPE"];
			}
			set
			{
				ViewState["CURPSWVIEWTYPE"] = value;
			}

		}

		public Literal ltrResult { get; set; }

		protected void Page_Load(object sender, EventArgs e)
		{
			//pnlResetPswInvalidkey.Visible = !String.IsNullOrEmpty(PasswordVerifyKey);
			//if (String.IsNullOrEmpty(PasswordVerifyKey))
			//	pnlResetPswInvalidkey.Visible = true;

			//pnlResetPswView.Visible = !pnlResetPswInvalidkey.Visible;

		}
		protected void Page_PreRender(object sender, EventArgs e)
		{
			plcResetPswInvalidkey.Visible = CurPswViewType == PswViewType.InvalidKey;
			//if (String.IsNullOrEmpty(PasswordVerifyKey))
			//	pnlResetPswInvalidkey.Visible = true;

			plcResetPswView.Visible = CurPswViewType == PswViewType.ResetPassword;
			plcResetPswSuccess.Visible = CurPswViewType == PswViewType.ResetSuccess;

		}


		/// <summary>
		/// Reset account password from email generated by forgot password.
		/// </summary>
		/// <param name="sender"></param>
		/// <param name="e"></param>
		protected void btnSetPassword_Click(object sender, EventArgs e)
		{
			if (String.IsNullOrEmpty(PasswordVerifyKey))//(String.IsNullOrEmpty(Request.QueryString["verify"]))
			{
				ltrResult.Text = "Invalid key!!";
				//CurViewType = "1";
				return;
			}

			if (String.IsNullOrEmpty(txtSetPassword1.Text))
			{
				ltrResult.Text = "Invalid password 1";
				return;
			}
			else if (String.IsNullOrEmpty(txtSetPassword2.Text))
			{
				ltrResult.Text = "Invalid Password 2";
				return;
			}
			else if (txtSetPassword1.Text != txtSetPassword2.Text)
			{
				ltrResult.Text = "Password 1 and Password 2 are not matching";
				return;
			}

			string verifyKey = PasswordVerifyKey;//  Request.QueryString["verify"];
										 // Validate key
			string sql = $"select top 1 * from VerifyLog where verify_key = @key and expire_time >= getutcdate() order by id desc";
			List<KeyValuePair<string, object>> prms = new List<KeyValuePair<string, object>>();
			prms.Add(new KeyValuePair<string, object>("key", verifyKey));
			var tblUserLog = DataService.GetDataTable(sql, parmeters: prms);
			if (tblUserLog == null || tblUserLog.Rows.Count < 1)
			{
				CurPswViewType = PswViewType.InvalidKey;
				return;
			}

			string strmobile = tblUserLog.Rows[0]["mobile"].ToString();
			string strEmail = tblUserLog.Rows[0]["email"].ToString();
			sql = "select top 1 * from [User] where email = @email and mobile = @mobile";
			prms.Add(new KeyValuePair<string, object>("email", strEmail));
			prms.Add(new KeyValuePair<string, object>("mobile", strmobile));
			var tblUser = DataService.GetDataTable(sql, parmeters: prms);
			// Validate user.
			if (tblUser == null || tblUser.Rows.Count < 1)
			{
				CurPswViewType = PswViewType.InvalidKey;
				return;
			}
			// Generate new password
			string saltKey = EncryptionService.CreateSaltKey(5);
			string strEncPsw = EncryptionService.CreatePasswordHash(txtSetPassword1.Text, saltKey);

			// Set new password
			sql = "UPDATE [User] SET [Password] = @psw, [PasswordSalt] = @saltKey, [PasswordType] = 2, hasVerifiedEmail=1  WHERE id= @id; UPDATE VerifyLog SET expire_time=NULL, verify_status='verified' where verify_key = @key";
			prms = new List<KeyValuePair<string, object>>();
			prms.Add(new KeyValuePair<string, object>("psw", strEncPsw));
			prms.Add(new KeyValuePair<string, object>("saltKey", saltKey));
			prms.Add(new KeyValuePair<string, object>("id", (int)tblUser.Rows[0]["id"]));
			prms.Add(new KeyValuePair<string, object>("key", verifyKey));
			DataService.ExecuteSql(sql, parmeters: prms);
			CurPswViewType = PswViewType.ResetSuccess;

			// Authenticate user.
			User user = null;
			var loginResult = UserService.ValidateCustomer(tblUser.Rows[0]["email"].ToString(), txtSetPassword1.Text, out user);
			switch (loginResult)
			{
				case CustomerLoginResults.Successful:
					{
						FormsAuthenticationService.SignIn(user, true);
						Service.UserService.CachedDefaultUser = user;
						ltrlSetPswContinue.Text = "Please continue to next step for creating your store.";
						hlSetPswNavigate.NavigateUrl = "/";
						hlSetPswNavigate.Text = "Continue";

						//if (CurGSTStatus == Services.GSTStatus.VerificationSkipped && !String.IsNullOrEmpty(txtGSTNumber.Value))
						//{
						//	try
						//	{
						//		string sqlInsertVerifyLog = "INSERT INTO VerifyLog(verify_key, verify_code, verify_type, verify_status, UserId) VALUES(@verify_key, @verify_code, @verify_type, @verify_status, @UserId);";
						//		List<KeyValuePair<string, object>> prmsInsertVerifyLog = new List<KeyValuePair<string, object>>();
						//		prmsInsertVerifyLog.Add(new KeyValuePair<string, object>("verify_key", txtGSTNumber.Value));
						//		prmsInsertVerifyLog.Add(new KeyValuePair<string, object>("verify_code", -1));
						//		prmsInsertVerifyLog.Add(new KeyValuePair<string, object>("verify_type", 3));
						//		prmsInsertVerifyLog.Add(new KeyValuePair<string, object>("verify_status", $"{(ConfigurationManager.AppSettings.Get("VATType") == "2" ? "GST" : "VAT")} Verification Pending"));
						//		prmsInsertVerifyLog.Add(new KeyValuePair<string, object>("UserId", user.Id));
						//		DataService.ExecuteSql(sqlInsertVerifyLog, parmeters: prmsInsertVerifyLog);
						//	}
						//	catch (Exception ex) { this.LogError(ex.Message); }

						//}
						Response.Redirect("/");
						break;
					}
				default:
					ltrlSetPswContinue.Text = "Please login with your credentials.";
					hlSetPswNavigate.NavigateUrl = "/login";
					hlSetPswNavigate.Text = "Login";
					break;
			}

		}

		public enum PswViewType
		{
			ResetPassword,
			InvalidKey,
			ResetSuccess
		}

	}
}