<?php

namespace App\Status;

use Exception;

final class QugeoSourceOrderStatus
{
     public const QUGEO_TO_B2C_ORDER_STATUS_READY_FOR_DELIVERY = 9 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_BOY_POLLED = 11 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_POLL_REJECT_NORESPONSE = 12 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_MANUAL_SCHEDULE = 13 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_BOY_ASSIGNED = 14 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_PICKUP_FAILED = 10 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_OUT_FOR_DELIVERY = 15 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_DELIVERY_FAILED = 16 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_DELIVERED_NOT_CONFIRMED = 17 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_DELIVERY_CONFIRMED = 18 ;
     public const QUGEO_TO_B2C_ORDER_STATUS_PICKED_UP = 20 ;
    
     public const QUGEO_TO_B2B_ORDER_STATUS_READY_FOR_DELIVERY = 8 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_BOY_POLLED = 21 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_POLL_REJECT_NORESPONSE = 22 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_MANUAL_SCHEDULE = 23 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_BOY_ASSIGNED = 24 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_PICKUP_FAILED = 25 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_OUT_FOR_DELIVERY = 26 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_DELIVERY_FAILED = 27 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_DELIVERED_NOT_CONFIRMED = 28 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_DELIVERY_CONFIRMED = 29 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_PICKED_UP = 30 ;
    
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_READY_FOR_DELIVERY = 20 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_BOY_POLLED = 21 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_POLL_REJECT_NORESPONSE = 22 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_MANUAL_SCHEDULE = 23 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_BOY_ASSIGNED = 24 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_PICKUP_FAILED = 25 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_OUT_FOR_DELIVERY = 26 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_DELIVERY_FAILED = 27 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_DELIVERED_NOT_CONFIRMED = 28 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_DELIVERY_CONFIRMED = 29 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_PICKED_UP = 30 ;
     public const QUGEO_TO_CPD2BR_ORDER_STATUS_OUT_DELIVERY = 26 ;
     public const QUGEO_TO_B2B_ORDER_STATUS_OUT_DELIVERY = 26 ;
    
     private function __construct()
    {
        throw new Exception('Cannot instantiate StatusCode') ;
    }

}